### ISSUE TITLE
Getting compile error after upgrade -- 

### ISSUE THREAD

**Issue by sjmcdowall** [VoltaireApp/icons_helper#1]
Hey there!  0.0.8 is giving an error in the latest Dart / Flutter with the error being:

```
Compiler message:
file:///Users/sjm/Development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/icons_helper-0.0.8/lib/icons_helper.dart:963:31: Error: Getter not
found: 'rendact'.
  'rendact': FontAwesomeIcons.rendact,
                                                      ^^^^^^^
```

**Comment by sjmcdowall** [comment]
And -- solved -- had to issue this set of commands:

$ flutter clean
$ rm -rf  ~/Development/tools/flutter/.pub-cache/hosted
$ flutter packages get 

Then it works again .. strange!

**Comment by sjmcdowall** [comment]
OK -- I was maybe a bit premature -- for some reason doing a "flutter run " works but when I do a flutter build it does not :( 

flutter build ios --release lib/main_preview.dart      

    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...

    Compiler message:
    file:///Users/sjm/Development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/icons_helper-0.0.8/lib/icons_helper.dart:963:31: Error: Getter
    not found: 'rendact'.
      'rendact': FontAwesomeIcons.rendact,
                                  ^^^^^^^
    Compiler terminated unexpectedly.
    Failed to build /Users/sjm/work/mm/mms4/mobile.

Sigh.. any ideas here?

**Comment by sjmcdowall** [comment]
OK -- looking -- icons_helper is looking for rendact as an icon -- looking at font_awesome_flutter 8.2.0 (the latest) that is NOT a valid Icon anymore .. need to remove it from here I think?

**Comment by sjmcdowall** [comment]
PR - https://github.com/VoltaireApp/icons_helper/pull/2  created

**Comment by sjmcdowall** [comment]
@24601 -- Hello!?

**Comment by frankps** [comment]
Hello nice work, but...
With a new project, I have exact the same problem:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/icons_helper-0.0.8/lib/icons_helper.dart:963:31: Error: Getter not found: 'rendact'.
  'rendact': FontAwesomeIcons.rendact,

**Comment by sjmcdowall** [comment]
Just use mine : 

  icons_helper:
    git: git://github.com/sjmcdowall/icons_helper

**Comment by frankps** [comment]
@sjmcdowall   Thanks for your feedback! I will try!!

**Comment by vinetsac** [comment]
Excelente aporte!

**Comment by 24601** [comment]
See #3
