### ISSUE TITLE
So is this Abandon  Ware now? 

### ISSUE THREAD

**Issue by sjmcdowall** [VoltaireApp/icons_helper#3]
Looks like a dead project, which is too bad...

**Comment by HeyYouNotYouYou** [comment]
hahaha I have the same problem with rendact :(

**Comment by sjmcdowall** [comment]
I fixed it in my fork -- you can use this:

  icons_helper:
    git:
      url: git://github.com/sjmcdowall/icons_helper


Should work

**Comment by dennisbappert** [comment]
Your fork is broken for me, I forked it again and fixed the compiler issues.

´´´
icons_helper:
    git:
      url: git://github.com/dennisbappert/icons_helper
´´´

**Comment by sjmcdowall** [comment]
What issues did you have in my fork @dennisbappert  ??  Can you share the error messages?

**Comment by 24601** [comment]
Not so much "abandonware" as "didn't have time to prioritize this ware" but we have an internal need to use it in Dart 2.x and will likely update it in the next few days. 

Thanks for the interaction & fixes above, I may PR some of those if the fix the issue. 

But we will likely have this fixed this weekend.

**Comment by 24601** [comment]
@sjmcdowall and @dennisbappert - thank you both for your contribution/changes. I've included them and I've also updated the Font Awesome support to 5.5, this now builds on current flutter/dart.
